# Generated by Django 4.2.1 on 2023-05-24 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50, verbose_name='Автор: ')),
                ('age', models.CharField(max_length=2, verbose_name='Вік: ')),
                ('sex', models.CharField(choices=[('M', 'Чоловік'), ('F', 'Жінка')], max_length=1, verbose_name='Стать:')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%Y', verbose_name='Світлина: ')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок: ')),
                ('place', models.CharField(max_length=150, verbose_name='Місце подорожі: ')),
                ('description', models.TextField(max_length=2000, verbose_name='Опис: ')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.validate_integer], verbose_name='Тел: ')),
                ('mail', models.EmailField(max_length=20, validators=[django.core.validators.EmailValidator()], verbose_name='Емайл:')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації:')),
            ],
            options={
                'verbose_name': 'Запиc',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50, verbose_name='Автор:')),
                ('text_comments', models.TextField(max_length=500, verbose_name='Текст коменту:')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.post', verbose_name='Публікація')),
            ],
            options={
                'verbose_name': 'Коментарій',
                'verbose_name_plural': 'Коментарії',
            },
        ),
    ]
