# Generated by Django 4.2.1 on 2023-05-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_alter_post_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
    ]
