# Generated by Django 4.2.1 on 2023-06-10 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.CharField(max_length=2, verbose_name='Вік '),
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.CharField(max_length=50, verbose_name='Автор '),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації '),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Опис '),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y', verbose_name='Світлина '),
        ),
        migrations.AlterField(
            model_name='post',
            name='mail',
            field=models.EmailField(max_length=20, validators=[django.core.validators.EmailValidator()], verbose_name='Емайл '),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.validate_integer], verbose_name='Тел '),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.CharField(blank=True, choices=[('UA', 'Україна'), ('AU', 'Австралія'), ('AT', 'Австрія'), ('BE', 'Бельгія'), ('BG', 'Болгарія'), ('BR', 'Бразилія'), ('HU', 'Угорщина'), ('DE', 'Німеччина'), ('GR', 'Греція'), ('DK', 'Данія'), ('EG', 'Єгипет'), ('IL', 'Ізраїль'), ('IN', 'Індія'), ('IE', 'Ірландія'), ('IS', 'Ісландія'), ('ES', 'Іспанія'), ('IT', 'Італія'), ('CY', 'Кіпр'), ('CN', 'Китай'), ('CO', 'Колумбія'), ('LV', 'Латвія'), ('LT', 'Литва'), ('LU', 'Люксембург'), ('MK', 'Північна Македонія'), ('MY', 'Малайзія'), ('MT', 'Мальта'), ('MX', 'Мексика'), ('MA', 'Марокко'), ('NZ', 'Нова Зеландія'), ('NO', 'Норвегія'), ('PL', 'Польща'), ('PT', 'Португалія'), ('RO', 'Румунія'), ('SG', 'Сінгапур'), ('SK', 'Словаччина'), ('SI', 'Словенія'), ('US', 'Сполучені Штати Америки'), ('TH', 'Таїланд'), ('TN', 'Туніс'), ('TR', 'Туреччина'), ('UY', 'Уругвай'), ('PH', 'Філіппіни'), ('FI', 'Фінляндія'), ('FR', 'Франція'), ('HR', 'Хорватія'), ('CZ', 'Чехія'), ('CL', 'Чилі'), ('CH', 'Швейцарія'), ('SE', 'Швеція'), ('EC', 'Еквадор'), ('ZA', 'ПАР'), ('JP', 'Японія'), ('PY', 'Парагвай'), ('PE', 'Перу')], max_length=150, null=True, verbose_name='Місце подорожі '),
        ),
        migrations.AlterField(
            model_name='post',
            name='sex',
            field=models.CharField(choices=[('M', 'Чоловік'), ('F', 'Жінка')], max_length=1, verbose_name='Стать '),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок '),
        ),
    ]
